version: "3.9"

services:
  balancer_influxdb:
    image: influxdb:2.1
    ports:
      - "8086:8086"
    env_file:
      - ../env.influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
  balancer_python:
    image: python:3.10.1-alpine3.15
