{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Real time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"balancer\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"real_time\")\n  |> filter(fn: (r) => strings.hasPrefix(v: r[\"_field\"], prefix: \"real_time_\"))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  "
    }
   ]
  },
  { "title": "Physical details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Phase Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"balancer\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"real_time\")\n  |> filter(fn: (r) => r[\"_field\"] == \"meter_voltage_ac_phase_1\" or r[\"_field\"] == \"meter_voltage_ac_phase_2\" or r[\"_field\"] == \"meter_voltage_ac_phase_3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  "
    }
   ]
  },
  {
   "title": "Phase To Phase Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"balancer\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"real_time\")\n  |> filter(fn: (r) => r[\"_field\"] == \"meter_voltage_ac_phase_12\" or r[\"_field\"] == \"meter_voltage_ac_phase_23\" or r[\"_field\"] == \"meter_voltage_ac_phase_31\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  "
    }
   ]
  },
  {
   "title": "Current AC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"balancer\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"real_time\")\n  |> filter(fn: (r) => strings.hasPrefix(v: r[\"_field\"], prefix: \"meter_current_ac_phase_\"))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  "
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"balancer\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"real_time\")\n  |> filter(fn: (r) => r[\"_field\"] == \"meter_frequency_average\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  "
    }
   ]
  },
  {
   "title": "Power details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Phase Power",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "query": "import \"strings\"\n\nfrom(bucket: \"balancer\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"real_time\")\n  |> filter(fn: (r) => strings.hasPrefix(v: r[\"_field\"], prefix: \"meter_power_real_phase_\"))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  "
      }
     ]
    },
    {
     "title": "Real Power Sum",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "query": "from(bucket: \"balancer\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"real_time\")\n  |> filter(fn: (r) => r[\"_field\"] == \"meter_power_real_sum\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  "
      }
     ]
    }
   ]
  }
 ]
}